CREATE TABLE USUARIOS(
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL, 
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	RUT VARCHAR(13) NOT NULL UNIQUE,
	ESTADO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE CUENTAS(
	ID SERIAL PRIMARY KEY,
	ID_USUARIO INTEGER NOT NULL REFERENCES USUARIOS(ID),
	N_CUENTA VARCHAR(25) NOT NULL UNIQUE,
	TIPO_CUENTA VARCHAR(50) NOT NULL,
	SALDO NUMERIC(11, 2) NOT NULL DEFAULT 0 CHECK(SALDO >=0)
);

select * from usuarios

--INSERT USUARIOS

INSERT INTO USUARIOS VALUES (default, 'Pedro', 'Soto', 'pedro@gmail.com', '11.111.111-1', default),
(default, 'Rodrigo', 'Sepulveda', 'rodrigo@gmail.com', '22.222.222-2', default);


select * from cuentaS;
--INSERT CUENTAS

insert into cuentas values(DEFAULT, 1, '1111-1111', 'Cuenta Corriente', 500000),
(DEFAULT, 2, '2222-2222', 'Cuenta Corriente', 750000);



CREATE TABLE TRANSACCIONES(
	ID SERIAL PRIMARY KEY,
	FECHA TIMESTAMP NOT NULL DEFAULT NOW(),
	cuenta_origen VARCHAR(25) NOT NULL REFERENCES CUENTAS(N_CUENTA),
	rut_remitente VARCHAR(13) NOT NULL REFERENCES usuarios(rut),
	rut_destinatario VARCHAR(13) NOT NULL REFERENCES usuarios(rut),
	cuenta_destino VARCHAR(25) NOT NULL REFERENCES CUENTAS(N_CUENTA),
	tipo_transaccion VARCHAR(50) NOT NULL, 
	glosa VARCHAR(100),
	monto NUMERIC(11, 2) NOT NULL CHECK(monto > 0)
);


--EJEMPLO TRANSACCIONES

select * from transacciones;
select * from cuentas;
SELECT * FROM USUARIOS;


--TRANSFERIR DESDE LA CUENTA 1111-1111 A LA CUENTA 2222-2222 UN TOTAL DE 150.000

BEGIN;
UPDATE CUENTAS SET SALDO = SALDO - 150000 WHERE N_CUENTA = '1111-1111';
UPDATE CUENTAS SET SALDO = SALDO + 150000 WHERE N_CUENTA = '2222-2222';

INSERT INTO TRANSACCIONES VALUES
(DEFAULT, DEFAULT, '1111-1111', '11.111.111-1', '22.222.222-2','2222-2222', 'Transferencia', 'pago de deuda.', 150000);
COMMIT;
ROLLBACK;